### ISSUE TITLE
Gran Turismo PSP

### ISSUE THREAD

**Issue by Shy-Doge** [TheOfficialFloW/GePatch#1]
Some slow downs, sometimes the screen gets black when loading in menus, some of the cameras in game are weird but the third person one is fine. its all fine but that, awesome work!

**Comment by vietcuongk99** [comment]
i think you should mention it in spreadsheet [https://docs.google.com/spreadsheets/d/1aZlmKwELcdpCb9ezI5iRfgcX9hoGxgL4tNC-673aKqk/edit#gid=0](url)

**Comment by Shy-Doge** [comment]
People already did it for that game, sorry for creating this, didnt realize the spreadsheet.
