### ISSUE TITLE
ABM updating and Adrenaline 7

### ISSUE THREAD

**Issue by BenTGOC** [TheOfficialFloW/GePatch#12]
I'm curious to know if there are any other dependencies that Bubbles Manager uses. Is there a possibility that the sce_module folder in ADRBUBMAN can be updated similarly to updating Adrenaline so that Bubbles can be used without it downgrading?

**Comment by ShroomKing** [comment]
ABM relies on AdrenalineBubbleBooter by leecherman, you have to wait for it to get updated.

He provides the source for his changes so I don't really understand why it wasn't merged into adrenaline/master yet but oh well.

**Comment by Schaefers** [comment]
Good news, Adrenaline Bubble Booter has been updated.  https://sites.google.com/site/theleecherman/adrbubblebooter/vpkedition
Moreover, I think @BenTGOC created the issue in the wrong issue tracker...

**Comment by BenTGOC** [comment]
> Good news, Adrenaline Bubble Booter has been updated. https://sites.google.com/site/theleecherman/adrbubblebooter/vpkedition
> Moreover, I think @BenTGOC created the issue in the wrong issue tracker...

Probably, but, being as the issue was already noted by the 0.18.1 release notes, I was just asking a question to better understand the program. Shoot, I'd even downloaded the source code for ABM to see if I could mess with it myself, which I couldn't because I'm fairly lame. I'd also considered that leecherman and TheFloW had already been in contact, so....thanks for letting me know about the update.
