### ISSUE TITLE
medal of honor Heroes!   polygon lost for closer camera

### ISSUE THREAD

**Issue by tee4341** [TheOfficialFloW/GePatch#18]
fps is best for ge_patch I very like!!!   but. medal of honor Heroes!   polygon lost for closer **camera** please fix!!
https://youtu.be/OScBOi-XjOU

thankkkkkkkk. youuuuuuu.......!!
...

**Comment by Girotin** [comment]
@tee4341 Dude he made an public file for compatibility tests, please stop making issue topics for one specific game, and add them to it's section on the list. 

https://docs.google.com/spreadsheets/d/1aZlmKwELcdpCb9ezI5iRfgcX9hoGxgL4tNC-673aKqk/edit#gid=0
