### ISSUE TITLE
add native psvita res for psp xmb in adrenaline

### ISSUE THREAD

**Issue by crazy2k4** [TheOfficialFloW/GePatch#4]
i'm put same txt line(ms0:seplugins/ge_patch.prx 1) in vsh.txt,and xmb looks great,but crashes psvita

**Comment by AceCuba** [comment]
delete all plugins in vsh.txt and game.txt leve the ms0:seplugins/ge_patch.prx 1) only .

**Comment by crazy2k4** [comment]
> 
> 
> delete all plugins in vsh.txt and game.txt leve the ms0:seplugins/ge_patch.prx 1) only .

i do it,but same crash,this plugin is designed for use in game.txt only,for now...

**Comment by AceCuba** [comment]
Nop the 0.15ver of the plguin work on the xmb at least its working fine for my on my psvita fat enso 3.65 . Only problems are vsh recovery menu don't show and the gameboot animation it's boogie . Disable Sony logo at boot and gameboot on the recovery menu and everything will work

**Comment by crazy2k4** [comment]
> 
> 
> Nop the 0.15ver of the plguin work on the xmb at least its working fine for my on my psvita fat enso 3.65 . Only problems are vsh recovery menu don't show and the gameboot animation it's boogie . Disable Sony logo at boot and gameboot on the recovery menu and everything will work

thank you very much

**Comment by AceCuba** [comment]
Your welcome its amazing what theflow just achive on the psvita
