### ISSUE TITLE
does GePatch work in pops.txt?

### ISSUE THREAD

**Issue by 0lorak** [TheOfficialFloW/GePatch#5]
I have enabled this plugin in pops.txt, then launched FFVIII but nothing was rendered on the screen.
Is it possible to make it compatible PS1 games?
Anyway, thanks for this plugin.

**Comment by AceCuba** [comment]
just put the plugin only on the game.txt and some ps1 games will be impruve . i test the ff7 and ff9

**Comment by TheOfficialFloW** [comment]
No it doesn't...
