### ISSUE TITLE
非常感谢您的辛苦付出Thank you very much for your hard work

### ISSUE THREAD

**Issue by zgj3880888** [TheOfficialFloW/GePatch#9]
我会把一些游戏的测试情况发上来，以供您查缺补漏之用
I'll send you the test results of some games for your reference

**Comment by fanliv** [comment]
fill the results here bro 
https://docs.google.com/spreadsheets/d/1aZlmKwELcdpCb9ezI5iRfgcX9hoGxgL4tNC-673aKqk/edit#gid=0

**Comment by masterrite** [comment]
他是越南人你打中文干什么？

**Comment by zgj3880888** [comment]
我是中国人！怎么可能是越南
 
---原始邮件---
发件人: "masterrite"<notifications@github.com&gt;
发送时间: 2020年10月3日(星期六) 上午6:12
收件人: "TheOfficialFloW/GePatch"<GePatch@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"zgj3880888"<719067002@qq.com&gt;;
主题: Re: [TheOfficialFloW/GePatch] 非常感谢您的辛苦付出Thank you very much for your hard work (#9)




 
他是越南人你打中文干什么？

**Comment by masterrite** [comment]
别蠢了 TheFlow在Twitter上是Andy Nguyen
